---
title: "Model Description"
author: "Bob Verity"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Model Description"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Overview

SIMPLEGEN works by making a clean break between the generation of *P. falciparum* epidemiological data and the generation of genetic data. Epidemiological data is generated from a transmission model, which is then stored in a "transmission record" detailing who infected whom. The user then specifies the IDs of individuals from which to sample genotypes at a particular point in time (or at multiple points in time). The transmission record is then pruned down to just the historical transmission events that ultimately lead up to these sampled individuals - all other transmission events are discarded, leading to a much smaller transmission record. Finally, genetic data is generated from the pruned transmission record. Genetic parameters, such as the number of loci and the error rate, can be specified at this final stage.

SIMPLEGEN works with transmission records generated from *any* model, just as long as the format is correct. However, a fairly complete transmission model is included in the program. Here we describe the transmission model, the format of the transmission record, the pruning process, and the generation of genetic data.


## Transmission model

The SIMPLEGEN transmission model is closely aligned to the Griffin *et al.* (2016) model, but has some key differences both in assumptions and implementation. The model is designed to be a minimally sufficient description of the transmission cycle, capturing the majority of important features that are required for simulations to match observed data, but otherwise leaving out details. It is also designed to be highly flexible, allowing the user to specify complete distributions where possible rather than using fixed values.

### Inoculations and host states

The most important concept in the model is the separation of 1) the infection state of a human host, 2) the individual states of infections that a human host receives, referred to as "inoculations", and 3) the genotypes within an individual. For purely epidemiological transmission models we can choose to focus on 1), as we only care about inoculations to the extent that they prolong the host infected state. However, for SIMPLEGEN we need to track both 1) and 2) in order to be able to generate 3) from the pruned transmission record.

We define an inoculation as a population of parasites that are passed from mosquito to human host upon successful infection. Each host within SIMPLEGEN can be be thought of having multiple inoculation "slots", and each new inoculation falls into a new slot. There are a finite number of slots available per host, defined by `max_inoculations`, but for most applications we can set this number to be large enough that hosts never saturate all their slots.

Each inoculation can be thought of as an independent episode of malaria that goes through the following stages: 1) liver stage, 2) acute blood stage, 3) chronic blood stage, 4) recovery. Inoculations can pass through all four stages, or they can pass directly from 1) to 3), and also from 2) to 4) depending on the model parameters. The acute stage essentially represents the symptomatic stage of infection, although the word "acute" has been used rather than "symptomatic" to avoid forcing a clinical interpretation on the model. The chronic stage is designed to capture long-lasting infections, including possible asymptomatic and/or sub-patent stages.

The state of a host is defined directly from the state of its inoculations. If there are any acute inoculations then the host is in the acute stage. Otherwise, if there are any chronic inoculations then the host is in the chronic stage. Otherwise, if there are any liver stage inoculations then the host is in the liver stage. Otherwise the host is in the susceptible stage. Thus, the state of the host roughly corresponds to the *most serious* of the inoculations it holds.

### Flexible distributions

In a standard compartmental model there is a constant probability of moving between states, leading to exponential waiting times in each state. In SIMPLEGEN the user can define probability distributions in a more flexible way, allowing them to vary from one inoculation to the next. For example, the `prob_infection` parameter specifies the probability of an infectious bite taking hold (leading to a new inoculation). If this is defined as a vector then the first value is used for the first infectious bite, the second value for the second bite, etc. until the final value which is used for all remaining bites. Hence, infection-blocking immunity can be modelled by using a vector of decreasing probabilities. Similarly, the `duration_chronic` parameter can be input as a single vector, in which case it specifies the daily probability of leaving the chronic phase, or as a list of vectors, in which case the model steps through the distributions for each new inoculation.

Parameters that can be varied include:

- the probability of infection, given a bite from an infectious mosquito
- the probability of going to acute stage vs. directly to chronic stage
- the probability of an acute infection going to chronic stage on recovery vs. directly to susceptible
- the duration of acute and chronic infection
- the probability of being treated in the acute and chronic stages
- the duration of treatment prophylaxis
- the onward infectivity of the acute and chronic stages
- detectability by microscopy and PCR in the acute and chronic stages

### Treatment

The exception to the rule that inoculations are independent is treatment. Upon treatment, all blood stage inoculations are immediately cured, and the host enters a prophylactic stage in which no new inoculations are possible. Liver stage inoculations are not directly cured, however, inoculations that leave the liver stage while the host is in the prophylactic stage are considered immediately cured. Sexual stages are not directly cured, although the termination of the diseased stage will lead to the termination of the sexual stage after the appropriate lag.

Daily treatment probabilities apply independently for each inoculation. Thus, if a host has two inoculations, with daily treatment probabilities of 0.2 and 0.3, then the overall treatment probability is given by 1 - (1-0.2)*(1-0.3) = 0.44.

The raw daily treatment probabilities above are modified by host-specific accessibility parameters. For each host, accessibility is drawn from a Beta distribution with user-defined mean and variance. Accessibility values are drawn once at birth and apply for the lifetime of a host, representing long-term inequalities in access to treatment. For example, if the treatment accessibility of a host is 0.5, and the raw treatment probability on the current day is 0.8, then the final probability of seeking treatment on this day is 0.8*0.5 = 0.4 for that host.

### Infectivity and mosquitoes

The onward infectivity of an inoculation to mosquitoes also goes through acute and chronic stages, which are lagged from the asexual stages. For example, take an inoculation that transitions from liver stage to acute stage on day 20, then to chronic infection on day 40, then recovers on day 100. If the gametocyte lag parameter `g` is equal to 10 days then the inoculation will enter the acute infective stage on day 30, the chronic infective stage on day 50, and will become uninfective on day 110. The daily infectivity of the acute and chronic stages can be defined flexibly by the user (see above). The oveall infectivity of a host is taken to be the *maximum* of the infectivity of its inoculations.

Mosquitoes exist in three stages: susceptible, latently infected, and infectious. Upon biting an infectious human host and becoming infected, they enter the latent stage which has fixed duration `v` (the extrinsic incubation period). Upon leaving the latent stage they become infective to humans. Natural death occurs with constant rate `mu` throughout the mosquito lifetime, and every death is matched with a new birth in the susceptible stage, leading to a constant mosquito population size `M`.

### Demographics

The stable age distribution is calculated from life tables, which can be user-defined, or is taken from Mali demographic data by default. Human deaths are matched by new births, leading to a constant total human population size. Only natural death is considered, i.e. malaria does not lead to increased chance of death. Complete age distributions can be produced from the model at user-specified time points - for example the complete age distribution of clinical incidence.

### Migration

All of the model description above applies to a single epidemiological unit - a single *deme*. Human migration is modelled as a stochastic process in which hosts move between demes. To make this process as realistic as possible, migration probabilities can vary by age as well as by source/destination. Migration events are seen as temporary trips of defined duration before returning to the home deme. Hence, migration can capture everything from short trips to nearby villages to long-distance seasonal migration patterns. Mosquito migration is not modelled.

For each deme, the overall probability of migration can be defined as a function of time. This is scaled by a factor that is defined separately for each one-year age group - for example, adults may migrate more than children. Given that migration occurs, the relative probability of migrating to each destination deme is defined using a deme-by-deme matrix, which is also free to vary over time. Finally, the trip duration can be specified between every pair of demes.


## The transmission record

TODO

## The genetic model

TODO


